import Link from 'next/link'
import React, { useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'

import { Auth, Hub } from "aws-amplify"
import { Button, Flex } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css'

import { useDispatch, useSelector } from 'react-redux'
import { signedIn, signedOut, justSignedUp } from '../slices/authSlice'
import { useRouter } from 'next/router';



function Navbar() {

  const dispatch = useDispatch()
  const authState = useSelector((state) => state.authState.value)

  const router = useRouter()

  useEffect(() => {
    Hub.listen('auth', ({ payload: { event, data } }) => {
      switch (event) {
        case 'signIn':
          dispatch(signedIn())
          router.push('/dashboard')
        case 'cognitoHostedUI':

          break;
        case 'signOut':
          dispatch(signedOut())
          break;
        case 'signUp':
          dispatch(justSignedUp())

          break;
        case 'signIn_failure':
        case 'cognitoHostedUI_failure':

          break;
      }


    });

    getUser();

    function getUser() {
      return Auth.currentAuthenticatedUser()
        .then(() => dispatch(signedIn()))
        .catch(() => dispatch(signedOut()));
    }

  }, []);

 

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <Flex
          width="100%"
          alignItems="center"
          justifyContent="space-between"
        >
          <Image
            
            src="/logo.png"
            alt="Picture of the author"
            width={50}
            height={50}
          />
          
            <Link href={'/'} className={router.pathname == "/" ? "active" : ""}>Home</Link>
            <Link href={'/dashboard'} className={router.pathname == "/dashboard" ? "active" : ""}>Dashboard</Link>
            <Link href={'/services'} className={router.pathname == "/services" ? "active" : ""}>Services</Link>
            <Link href={'/about'} className={router.pathname == "/about" ? "active" : ""}>About</Link>
            <Link href={'/profile'} className={router.pathname == "/profile" ? "active" : ""}>Profile</Link>

            
            {authState ? (
              <Button onClick={() => { Auth.signOut(); }}>Sign Out</Button>
            ) : (
              <Link href={'/login'}>Login</Link>
            )}
          
        </Flex>
      </nav>

    </div>

  )
}

export default Navbar